version: "3.8"

volumes:
  node_modules:
  postgres:

services:
  ui:
    image: node:14.8.0-alpine3.12
    ports:
      - 3000:8080
    working_dir: /app
    volumes:
      - ./ui:/app
      - node_modules:/app/node_modules
    command: yarn serve

  app:
    image: interview-school:development
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    env_file: ./docker/development/Envfile
    entrypoint: docker/entrypoint.sh
    links:
      - postgres
    volumes:
      - .:/app
      - /app/tmp
    command: bin/rails s

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data


  test:
    image: interview-school:development
    env_file: ./docker/test/Envfile
    entrypoint: docker/entrypoint.sh
    links:
      - postgres
    volumes:
      - .:/app
      - /app/tmp
