version: "3.8"
services:
  interview-school:
    image: mindr-interview-school
    ports:
      - "3000:3000"
    volumes:
      - ./app:/src/app:delegated
      - ./public:/src/public:cached
      - ./test:/src/test:delegated
      - ./config:/src/config:cached
      - ./db/migrate:/src/db/migrate:cached
      - ./Gemfile:/src/Gemfile:cached
      - ./Gemfile.lock:/src/Gemfile.lock:cached
