
common: &common
  adapter: postgresql
  username: postgres
  password: postgres
  host: postgres
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *common
  database: interview_school_development

test:
  <<: *common
  database: interview_school_test

production:
  <<: *common
  database: interview_school_production
